apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-slave
  namespace: jmeter
spec:
  replicas: 0
  selector:
    matchLabels:
      app: jmeter-slave
  template:
    metadata:
      labels:
        app: jmeter-slave
    spec:
      containers:
        - name: jmeter-slave
          image: yemax/jmeter-custom:1.0.1
          command: ["/docker-entrypoint.sh"]
          args: ["server"]
