apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-master
  namespace: jmeter
spec:
  replicas: 0
  selector:
    matchLabels:
      app: jmeter-master
  template:
    metadata:
      labels:
        app: jmeter-master
    spec:
      containers:
        - name: jmeter-master
          image: yemax/jmeter-custom:1.0.1
          command: ["/docker-entrypoint.sh"]
          args: ["master"]
