"""Report builder"""

from pathlib import Path
from datetime import datetime
from typing import List, Dict, Any
from ..parsers.url_parser import GrafanaDashboardContext
from ..processors.data_processor import PanelData


class ReportBuilder:
    """Build performance test reports"""
    
    def build_report(
        self,
        dashboard_title: str,
        context: GrafanaDashboardContext,
        panel_data_list: List[PanelData],
        ai_analysis: str
    ) -> str:
        """
        Build comprehensive report
        
        Args:
            dashboard_title: Dashboard title
            context: Dashboard context
            panel_data_list: List of processed panel data
            ai_analysis: AI analysis summary
            
        Returns:
            Report content as markdown
        """
        report = []
        
        # Header
        report.append(f"# Performance Test Report: {dashboard_title}")
        report.append("")
        report.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        report.append(f"**Test Duration:** {self._format_duration(context)}")
        report.append(f"**Dashboard URL:** {context.raw_url}")
        report.append("")
        
        # Executive Summary
        report.append("## 📊 Executive Summary")
        report.append("")
        report.append(ai_analysis)
        report.append("")
        
        # Panel Details
        report.append("## 📈 Panel Metrics")
        report.append("")
        
        for panel_data in panel_data_list:
            report.append(f"### {panel_data.panel_title}")
            report.append("")
            report.append(f"**Type:** {panel_data.panel_type}")
            report.append("")
            
            if panel_data.metrics:
                report.append("**Metrics:**")
                report.append("")
                for ref_id, metrics in panel_data.metrics.items():
                    if isinstance(metrics, dict) and 'error' not in metrics:
                        report.append(f"- **{ref_id}:**")
                        report.append(f"  - Min: {metrics.get('min', 'N/A')}")
                        report.append(f"  - Max: {metrics.get('max', 'N/A')}")
                        report.append(f"  - Avg: {metrics.get('avg', 'N/A'):.2f}" if isinstance(metrics.get('avg'), (int, float)) else f"  - Avg: N/A")
                        report.append(f"  - Latest: {metrics.get('latest', 'N/A')}")
                report.append("")
            else:
                report.append("*No metrics available*")
                report.append("")
        
        # Footer
        report.append("---")
        report.append("")
        report.append("*Report generated by Performance Report Agent*")
        
        return "\n".join(report)
    
    def export(
        self,
        report: str,
        output_dir: str = './reports',
        filename: str = None
    ) -> str:
        """
        Export report to file
        
        Args:
            report: Report content
            output_dir: Output directory
            filename: Optional filename (without extension)
            
        Returns:
            Path to exported file
        """
        # Create output directory
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)
        
        # Generate filename
        if not filename:
            filename = f"performance_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
        
        # Save as markdown
        file_path = output_path / f"{filename}.md"
        file_path.write_text(report, encoding='utf-8')
        
        return str(file_path)
    
    def _format_duration(self, context: GrafanaDashboardContext) -> str:
        """Format time duration"""
        duration = context.time_to - context.time_from
        hours = duration.total_seconds() / 3600
        minutes = (duration.total_seconds() % 3600) / 60
        
        if hours >= 1:
            return f"{hours:.1f} hours"
        else:
            return f"{minutes:.0f} minutes"

